// export const SET_ID = 'SET_ID'
// export const SET_CREATE_DATA = 'SET_CREATE_DATA'
// export const SET_MODIFY_DATE = 'SET_MODIFY_DATE'
// export const SET_AUTHOR = 'SET_AUTHOR'
// export const SET_FITTING_NAME = 'SET_FITTING_NAME'
// export const SET_SHIP_ID = 'SET_SHIP_ID'
// export const SET_COMMANDER_ID = 'SET_COMMANDER_ID'
// export const SET_COMMANDER_SKILL = 'SET_COMMANDER_SKILL'
// export const SET_UPGRADE = 'SET_UPGRADE'
// export const SET_TITLE = 'SET_TITLE'
// export const SET_DESCRIPTION = 'SET_DESCRIPTION'

enum actionType {
    SET_ID = 'SET_ID',
    SET_CREATE_DATA = 'SET_CREATE_DATA',
    SET_MODIFY_DATE = 'SET_MODIFY_DATE',
    SET_AUTHOR = 'SET_AUTHOR',
    SET_FITTING_NAME = 'SET_FITTING_NAME',
    SET_SHIP_ID = 'SET_SHIP_ID',
    SET_COMMANDER_ID = 'SET_COMMANDER_ID',
    SET_COMMANDER_SKILL = 'SET_COMMANDER_SKILL',
    SET_UPGRADE = 'SET_UPGRADE',
    SET_TITLE = 'SET_TITLE',
    SET_DESCRIPTION = 'SET_DESCRIPTION',
    SET_FITTING_EDITOR = 'SET_FITTING_EDITOR',
}

export default actionType